# Generated by Django 4.2.4 on 2023-09-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Wait for confirmation', 'Wait for confirmation'), ('Waiting for delivery', 'Waiting for delivery'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Delivering', max_length=30),
        ),
    ]
